version: '3.8'

services:
  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-1
    image: mysql-1:0.0.1
    ports:
      - "7820:7820"
    environment:
      - PORT=7820
    volumes:
      # Rend vos images et miniatures persistantes sur votre machine hôte
      - ./upload:/app/upload
    restart: unless-stopped
