name: Build & Deploy Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test de construction de l'image Docker
        run: |
          docker build -t my-sql:latest .

      - name: Configurer la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

      - name: Connexion et déploiement sur le VPS
        run: |
          ssh -i ~/.ssh/private_key \
              -o StrictHostKeyChecking=no \
              -o BatchMode=yes \
              ${{ secrets.VSP_DEFAULT }}@${{ secrets.VPS_IP }} << 'EOF'

            cd .test
            echo "---------------------------- git pull ------------------------------------"
            git pull

            echo "---------------------------- docker build --------------------------------"
            docker build -t my-sql:latest .

            echo "---------------------------- arrêt ancien conteneur ---------------------"
            docker stop my-sql 2>/dev/null || true
            docker rm   my-sql 2>/dev/null || true

            echo "---------------------------- lancement nouveau conteneur ----------------"
            docker run -d \
              --name my-sql \
              --restart unless-stopped \
              -p 7820:8080 \
              my-sql:latest

            docker ps
          EOF