name: Build Docker Image test

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # nous allons définir plutard une logique de lancement de l'image puis de test de connexion au conternaire

      - name: test de construction de l'image docker
        run: |
          docker build -t web-app:latest .

      - name: Configurer la clé SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Connexion et deploiement sur le VPS
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no -o BatchMode=yes ${{ secrets.VPS_DEFAULT }}@${{ secrets.VPS_IP }} << 'EOF'
            cd test
            echo "---------------------------- git pull ------------------------------------"
            git pull

            docker build -t test .
            docker run -p 7820:7820 users
            docker ps
          EOF


#

